[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "py37-tf-gpu115"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.7.*"
pip = ">=24.0,<25"

[pypi-dependencies]
tensorflow-gpu = "==1.15.0"
rdkit = ">=2023.3.2, <2024"
pandas = ">=1.1.5, <2"
numpy = ">=1.21.6, <2"
keras = ">=2.11.0, <3"
matplotlib = ">=3.5.3, <4"
scikit-learn = ">=1.0.2, <2"
